# Generated by Django 4.1 on 2024-08-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('catNo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Catalog Number')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('tle1', models.CharField(max_length=70, verbose_name='TLE Line 1')),
                ('tle2', models.CharField(max_length=70, verbose_name='TLE Line 2')),
                ('uplink', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Radio Uplink Frequency')),
                ('downlink', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Radio Downlink Frequency')),
                ('classification', models.CharField(max_length=30, verbose_name='Classification')),
            ],
        ),
    ]
